requires:
- category: "development"
  name: "toolchain"
  version: ">=0"

env:
- DISABLE_WARN_OUTSIDE_CONTAINER=1
- GOPATH=/go

package_dir: /docker-cli
prelude:
- |
   luet install shells/bash development/make utils/ca-certificates libs/libressl vcs/git lang/go && \
   git clone https://github.com/docker/cli.git && \
   cd cli && git checkout -b build v${PACKAGE_VERSION%\+*} && cd .. && \
   mkdir -p $GOPATH/src && \
   mv cli/vendor/* $GOPATH/src && \
   mv cli $GOPATH/src/github.com/docker


steps:
- | 
   mkdir -p /docker-cli/usr/bin && \
   cd $GOPATH/src/github.com/docker/cli && BUILDTIME=$(date --utc) make binary && \
   mv build/docker-linux-amd64 /docker-cli/usr/bin/docker
