requires:
- category: "X"
  name: "util-macros"
  version: ">=0"

env:
- CFLAGS="-g -O2 -I/include -I/usr/include -I/usr/include/X11 -static"
- CPPFLAGS="-I/include -I/usr/include -I/usr/include/X11 -static"
package_dir: /{{.Values.name}}
prelude:
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   luet install utils/autoconf utils/curl libs/zlib vcs/git development/automake development/pkg-config development/m4 \
   development/make system/musl-toolchain && \
   curl -L https://www.x.org/releases/individual/lib/{{.Values.name}}-$PACKAGE_VERSION.tar.bz2 -o {{.Values.name}}-${PACKAGE_VERSION}.tar.bz2 && \
   tar -xvf {{.Values.name}}-${PACKAGE_VERSION}.tar.bz2 -C ./ && mv {{.Values.name}}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   mkdir -p /${PACKAGE_NAME}

steps:
- |
   cd ${PACKAGE_NAME} && \
   ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var && \
   make DESTDIR=/${PACKAGE_NAME} && \
   make DESTDIR=/${PACKAGE_NAME} install && make install
